apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-ShaneYu
spec:
  displayName: ShaneYu
  author:
    name: ShaneYu
    website: https://github.com/ziangu/ShaneYu
  description: 源于禹州，面向世界。Shane Yu是一款为开发者打造的现代博客主题，关于专注与极致的分享空间，摒弃繁杂，回归本质。
  logo: /themes/theme-ShaneYu/assets/images/logo.png
  homepage: https://github.com/ziangu/ShaneYu
  repo: https://github.com/ziangu/ShaneYu
  settingName: "ShaneYu-setting"
  configMapName: "ShaneYu-configMap"
  version: 0.5.61
  requires: ">=2.20.0"
  issues: https://github.com/ziangu/ShaneYu/issues
  license:
    - name: "GPL-3.0"
      url: "https://github.com/ziangu/ShaneYu/blob/main/LICENSE"
  loginTemplate: "login.html"
  errorTemplates:
    notFound: "error/404.html"
    serverError: "error/500.html"
    error: "error/error.html"
